"""Reference and Lookup Tables

Revision ID: 764b898dfb49
Revises: ac54ab683614
Create Date: 2026-10-09 12:29:27.520721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '764b898dfb49'
down_revision: Union[str, Sequence[str], None] = 'ac54ab683614'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'building_categories',
        'category',
        type_=sa.String(length=24),  # New length
        existing_type=sa.String(),   # Old length
        existing_nullable=True
    )
    op.create_table('access_types',
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_access_types')),
    sa.UniqueConstraint('type', name=op.f('uq_access_types_type'))
    )
    op.create_table('accessibility_features',
    sa.Column('feature', sa.String(length=24), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accessibility_features')),
    sa.UniqueConstraint('feature', name=op.f('uq_accessibility_features_feature'))
    )
    op.bulk_insert(
        sa.table(
            'accessibility_features',
            sa.column('id', sa.Integer),
            sa.column('feature', sa.String)
        ),
        [
            {'id': 1, 'feature': 'entrance_ramp'},
            {'id': 2, 'feature': 'elevator'},
            {'id': 3, 'feature': 'automatic_door'},
            {'id': 4, 'feature': 'accessibile_parking'}
        ]
    )
    op.create_table('edge_types',
    sa.Column('type', sa.String(length=8), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_edge_types')),
    sa.UniqueConstraint('type', name=op.f('uq_edge_types_type'))
    )
    op.create_table('indoor_poi_types',
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_indoor_poi_types')),
    sa.UniqueConstraint('type', name=op.f('uq_indoor_poi_types_type'))
    )
    op.bulk_insert(
        sa.table(
            'indoor_poi_types',
            sa.column('id', sa.Integer),
            sa.column('type', sa.String)
        ),
        [
            {'id': 1, 'type': 'water_fountain'},
            {'id': 2, 'type': 'vending_machine_food'},
            {'id': 3, 'type': 'vending_machine_drinks'},
            {'id': 4, 'type': 'bathroom_men'},
            {'id': 5, 'type': 'bathroom_women'},
            {'id': 6, 'type': 'bathroom_unisex'},
            {'id': 7, 'type': 'bathroom_family'},
            {'id': 8, 'type': "mother's_room"},
            {'id': 9, 'type': 'front_desk'},
            {'id': 10, 'type': 'stairs'},
            {'id': 11, 'type': 'elevator'}
        ]
    )
    op.create_table('location_types',
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_location_types')),
    sa.UniqueConstraint('type', name=op.f('uq_location_types_type'))
    )
    op.bulk_insert(
        sa.table(
            'location_types',
            sa.column('id', sa.Integer),
            sa.column('type', sa.String)
        ),
        [
            {'id': 1, 'type': 'building'},
            {'id': 2, 'type': 'room'},
            {'id': 3, 'type': 'parking_lot'},
            {'id': 4, 'type': 'indoor_poi'},
            {'id': 5, 'type': 'outdoor_poi'}
        ]
    )
    op.create_table('office_categories',
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_office_categories')),
    sa.UniqueConstraint('category', name=op.f('uq_office_categories_category'))
    )
    op.bulk_insert(
        sa.table(
            'office_categories',
            sa.column('id', sa.Integer),
            sa.column('category', sa.String)
        ),
        [
            {'id': 1, 'category': 'professor'},
            {'id': 2, 'category': 'shared'},
            {'id': 3, 'category': 'administrative'},
            {'id': 4, 'category': 'service'},
            {'id': 5, 'category': 'miscellaneous'}
        ]
    )
    op.create_table('outdoor_poi_types',
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outdoor_poi_types')),
    sa.UniqueConstraint('type', name=op.f('uq_outdoor_poi_types_type'))
    )
    op.create_table('room_types',
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_room_types')),
    sa.UniqueConstraint('type', name=op.f('uq_room_types_type'))
    )
    op.bulk_insert(
        sa.table(
            'room_types',
            sa.column('id', sa.Integer),
            sa.column('type', sa.String)
        ),
        [
            {'id': 1, 'type': 'classroom'},
            {'id': 2, 'type': 'computer_lab'},
            {'id': 3, 'type': 'engineering_lab'},
            {'id': 4, 'type': 'chemistry_lab'},
            {'id': 5, 'type': 'radiation_lab'},
            {'id': 6, 'type': 'environmental_lab'},
            {'id': 7, 'type': 'physics_lab'},
            {'id': 8, 'type': 'research_lab'},
            {'id': 9, 'type': 'media_lab'},
            {'id': 10, 'type': 'robotics_lab'},
            {'id': 11, 'type': 'materials_lab'},
            {'id': 12, 'type': '3d_print_lab'},
            {'id': 13, 'type': 'optics_laser_lab'},
            {'id': 14, 'type': 'mechanical_engineering_lab'},
            {'id': 15, 'type': 'computer_study_lab'},
            {'id': 16, 'type': 'cybersecurity_lab'},
            {'id': 17, 'type': 'miscellaneous_lab'},
            {'id': 18, 'type': 'vehicle_shop'},
            {'id': 19, 'type': 'studio'},
            {'id': 20, 'type': 'office'},
            {'id': 21, 'type': 'workstation'},
            {'id': 22, 'type': 'auditorium'},
            {'id': 23, 'type': 'multi-purpose'},
            {'id': 24, 'type': 'restroom'},
            {'id': 25, 'type': 'restaurant'},
            {'id': 26, 'type': 'vending'},
            {'id': 27, 'type': 'information_technology'},
            {'id': 28, 'type': 'study'},
            {'id': 29, 'type': 'conference'},
            {'id': 30, 'type': 'recording'},
            {'id': 31, 'type': 'commons'},
            {'id': 32, 'type': 'lobby'},
            {'id': 33, 'type': 'esports'},
            {'id': 34, 'type': 'under_construction'},
            {'id': 35, 'type': 'undisclosed_support'},
            {'id': 36, 'type': 'miscellaneous'}
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room_types')
    op.drop_table('outdoor_poi_types')
    op.drop_table('office_categories')
    op.drop_table('location_types')
    op.drop_table('indoor_poi_types')
    op.drop_table('edge_types')
    op.drop_table('accessibility_features')
    op.drop_table('access_types')
    op.alter_column(
        'building_categories',
        'category',
        type_=sa.String(),                   # Previous length
        existing_type=sa.String(length=24),  # Current length
        existing_nullable=True
    )
    # ### end Alembic commands ###
