"""Indoor Nodes and Edges

Revision ID: 84076ec91240
Revises: 008d2a11fd8f
Create Date: 2026-09-27 14:44:51.715103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84076ec91240'
down_revision: Union[str, Sequence[str], None] = '008d2a11fd8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('num_floors', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_updated_by', sa.Integer(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['last_updated_by'], ['users.id'], name=op.f('fk_buildings_last_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_buildings')),
    sa.UniqueConstraint('name', name=op.f('uq_buildings_name'))
    )
    op.create_index(op.f('ix_buildings_code'), 'buildings', ['code'], unique=True)
    op.create_table('floors',
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('floor_num', sa.Integer(), nullable=False),
    sa.Column('svg', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_updated_by', sa.Integer(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], name=op.f('fk_floors_building_id_buildings')),
    sa.ForeignKeyConstraint(['last_updated_by'], ['users.id'], name=op.f('fk_floors_last_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_floors')),
    sa.UniqueConstraint('building_id', 'floor_num', name='uq_building_floor')
    )
    op.create_table('indoor_nodes',
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('floor_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_updated_by', sa.Integer(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], name=op.f('fk_indoor_nodes_building_id_buildings')),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], name=op.f('fk_indoor_nodes_floor_id_floors')),
    sa.ForeignKeyConstraint(['last_updated_by'], ['users.id'], name=op.f('fk_indoor_nodes_last_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_indoor_nodes'))
    )
    op.create_index('idx_indoor_node_building_floor', 'indoor_nodes', ['building_id', 'floor_id'], unique=False)
    op.create_table('indoor_edges',
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('floor_id', sa.Integer(), nullable=False),
    sa.Column('source_node_id', sa.Integer(), nullable=False),
    sa.Column('target_node_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_updated_by', sa.Integer(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], name=op.f('fk_indoor_edges_building_id_buildings')),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], name=op.f('fk_indoor_edges_floor_id_floors')),
    sa.ForeignKeyConstraint(['last_updated_by'], ['users.id'], name=op.f('fk_indoor_edges_last_updated_by_users')),
    sa.ForeignKeyConstraint(['source_node_id'], ['indoor_nodes.id'], name=op.f('fk_indoor_edges_source_node_id_indoor_nodes')),
    sa.ForeignKeyConstraint(['target_node_id'], ['indoor_nodes.id'], name=op.f('fk_indoor_edges_target_node_id_indoor_nodes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_indoor_edges')),
    sa.UniqueConstraint('source_node_id', 'target_node_id', name='uq_from_to')
    )
    op.create_index('idx_indoor_edge_building_floor', 'indoor_edges', ['building_id', 'floor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_indoor_edge_building_floor', table_name='indoor_edges')
    op.drop_table('indoor_edges')
    op.drop_index('idx_indoor_node_building_floor', table_name='indoor_nodes')
    op.drop_table('indoor_nodes')
    op.drop_table('floors')
    op.drop_index(op.f('ix_buildings_code'), table_name='buildings')
    op.drop_table('buildings')
    # ### end Alembic commands ###
