"""Node Types

Revision ID: ac54ab683614
Revises: 9fada1c7f431
Create Date: 2026-10-06 18:21:14.225242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac54ab683614'
down_revision: Union[str, Sequence[str], None] = '9fada1c7f431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Role seeding
node_types_seed_table = sa.table(
    'node_types',
    sa.column('id', sa.Integer),
    sa.column('type', sa.String)
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node_types',
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_node_types')),
    sa.UniqueConstraint('type', name=op.f('uq_node_types_type'))
    )
    op.bulk_insert(
        node_types_seed_table,
        [
            {'id': 1, 'type': 'room'},
            {'id': 2, 'type': 'room-door'},
            {'id': 3, 'type': 'hallway'},
            {'id': 4, 'type': 'stairs'},
            {'id': 5, 'type': 'elevator'},
            {'id': 6, 'type': 'entrance/exit'}
        ]
    )
    op.add_column('indoor_nodes', sa.Column('node_type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_indoor_nodes_node_type_id_node_types'), 'indoor_nodes', 'node_types', ['node_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_indoor_nodes_node_type_id_node_types'), 'indoor_nodes', type_='foreignkey')
    op.drop_column('indoor_nodes', 'node_type_id')
    op.drop_table('node_types')
    # ### end Alembic commands ###
