name: Build DB Migration

on:
  push:
    branches:
      - "**"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Upload migration artifacts
        uses: actions/upload-artifact@v7
        with:
          name: db-migration_${{ github.run_number }}
          path: | # TODO: Update to use a docker image
            alembic/versions
            alembic.ini
          retention-days: 90
